-- Antenna Phase 2A — stabilisation fixes from the first controlled buyer
-- test. Run once, after 006_observability.sql.
--
-- =============================================================================
-- Part 1 — fix "permission denied for table research_run_attempts"
-- =============================================================================
--
-- Existing security model, confirmed by inspecting every prior migration
-- (002-006) and schema.sql: Antenna has NO row-level security anywhere.
-- Every table is reachable only via the server-side Supabase client, which
-- always authenticates with SUPABASE_SERVICE_ROLE_KEY (see lib/supabase.ts)
-- — never an anon/publishable key, never from the browser. Access control
-- is enforced entirely by "only the server holds the key that can reach
-- Supabase at all," not by per-table RLS policies. `research_run_attempts`
-- is meant to follow that exact same model, like every other table here —
-- it just isn't reliably doing so yet in at least one live project.
--
-- The literal error text — "permission denied for table X" — is Postgres's
-- standard message for a missing table-level GRANT, not an RLS policy
-- rejection (an RLS violation on INSERT reads "new row violates row-level
-- security policy for table X" instead). So this is addressed directly: an
-- explicit GRANT to service_role, plus explicitly disabling RLS on this one
-- table to make it structurally identical to the other seven Antenna
-- tables (companies, signals, runs, theme_scores, theme_score_snapshots,
-- subscribers, daily_reports), none of which have RLS enabled. This is
-- NOT a blanket "disable RLS" change — it touches only this one table, and
-- only to match a pattern already used everywhere else in this schema.
--
-- Safe to re-run: GRANT and DISABLE ROW LEVEL SECURITY are both idempotent.

alter table research_run_attempts disable row level security;

grant select, insert, update, delete on research_run_attempts to service_role;
-- Belt-and-suspenders: an identity column's underlying sequence needs its
-- own USAGE grant separately from the table itself in Postgres, and its
-- autogenerated name isn't guaranteed. Scoped to service_role only (the
-- same role every write in this app already goes through) — this doesn't
-- extend what service_role can effectively reach, since it already has
-- full access to every other Antenna table by the same no-RLS pattern.
grant usage, select on all sequences in schema public to service_role;

-- =============================================================================
-- Part 2 — research run resilience: record whether a retry was needed
-- =============================================================================
--
-- lib/runResearch.ts now retries a timed-out/failed company once before
-- giving up on it (MAX_ATTEMPTS = 2). This column makes that visible per
-- organisation, alongside status/duration/tokens — "did this one need a
-- second try" is exactly the kind of signal Phase 5's observability model
-- exists to capture. Defaults to 0 so every pre-existing row (none exist
-- yet in practice, but in principle) reads as "no retry needed" rather
-- than null/unknown.

alter table research_run_attempts
  add column if not exists retry_count int not null default 0;
