// Phase 3B — the atomic unit of evidence across the product (theme pages'
// Market Evidence section and organisation pages' Latest Intelligence
// section both render lists of these). Spec, per the brief §5:
//   Organisation name / Organisation type: Buyer / Vendor / Signal headline
//   / Signal type / Intent score / Short summary / Source
//
// Field mapping (documented assumption — there is no dedicated "headline"
// column in the schema, and this phase does not add one per "avoid
// unnecessary database changes"): `signals.summary` is generated by the
// research prompt as "one sentence" (lib/research.ts) — that's used as the
// prominent headline. `signals.detail` is generated as "1-2 sentences of
// supporting context" — that's used as the short summary underneath. Both
// fields already existed before Phase 3B; nothing new is stored.
import Link from "next/link";
import InfoTooltip from "./InfoTooltip";
import { SCORE_COPY } from "@/lib/copy";
import { publisherLabel } from "@/lib/sourcePublisher";
import styles from "./SignalCard.module.css";

export type SignalCardData = {
  id: number;
  organisationName: string;
  organisationSlug: string;
  organisationTypeLabel: "Buyer" | "Vendor";
  headline: string;
  signalTypeLabel: string;
  intentScore: number | null;
  shortSummary: string | null;
  sourceUrl: string | null;
  sourceTitle: string | null;
};

export default function SignalCard({
  data,
  showOrganisationLink = true,
}: {
  data: SignalCardData;
  // Suppressed on an organisation's own page, where a signal card linking
  // back to the page it's already on would be a pointless self-link.
  showOrganisationLink?: boolean;
}) {
  const {
    organisationName,
    organisationSlug,
    organisationTypeLabel,
    headline,
    signalTypeLabel,
    intentScore,
    shortSummary,
    sourceUrl,
    sourceTitle,
  } = data;

  return (
    <div className={`card ${styles.card}`}>
      <div className={styles.top}>
        <div className={styles.org}>
          {showOrganisationLink ? (
            <Link href={`/organisations/${organisationSlug}`} className={styles.orgName}>
              {organisationName}
            </Link>
          ) : (
            <span className={styles.orgName}>{organisationName}</span>
          )}
          <span className="badge badge--neutral">{organisationTypeLabel}</span>
        </div>
        {intentScore !== null && (
          <span className={styles.intent}>
            Intent {intentScore}
            <InfoTooltip text={SCORE_COPY.signalIntent.lead} />
          </span>
        )}
      </div>

      <p className={styles.headline}>{headline}</p>
      <p className={styles.signalType}>Signal: {signalTypeLabel}</p>
      {shortSummary && <p className={styles.summary}>{shortSummary}</p>}

      {sourceUrl && (
        <a href={sourceUrl} target="_blank" rel="noopener noreferrer" className={styles.source}>
          Source: {publisherLabel(sourceUrl, sourceTitle) || "Open article"} ↗
        </a>
      )}
    </div>
  );
}
