// Phase 3B.1 — "Improve source presentation" (brief §5): show the actual
// publisher/outlet (e.g. "BBC News", "Financial Times"), not the specific
// article's own headline. `signals.source_title` is generated by the
// research prompt as "the article/press-release title" (lib/research.ts) —
// a specific headline, not an outlet name — so it's no longer the primary
// text shown. This derives a publisher label from `source_url`, which is
// existing metadata every signal already has; no new field, no new
// research/classification behaviour, presentation-layer only.
//
// A small lookup table covers outlets Antenna is likely to cite in media &
// entertainment technology coverage. Anything not in the table falls back
// to a cleaned-up version of its domain (e.g. "adobe.com" -> "Adobe.com") —
// honest and still identifies the source, just less polished than a curated
// name. Extend the table as unrecognised domains come up in practice; this
// is plain data, not methodology.
const KNOWN_PUBLISHERS: Record<string, string> = {
  "bbc.co.uk": "BBC News",
  "bbc.com": "BBC News",
  "ft.com": "Financial Times",
  "reuters.com": "Reuters",
  "bloomberg.com": "Bloomberg",
  "wsj.com": "The Wall Street Journal",
  "nytimes.com": "The New York Times",
  "netflixtechblog.com": "Netflix Technology Blog",
  "variety.com": "Variety",
  "deadline.com": "Deadline",
  "hollywoodreporter.com": "The Hollywood Reporter",
  "thewrap.com": "The Wrap",
  "techcrunch.com": "TechCrunch",
  "theverge.com": "The Verge",
  "adage.com": "Ad Age",
  "adweek.com": "Adweek",
  "ibc.org": "IBC365",
  "tvbeurope.com": "TVBEurope",
  "digitaltveurope.com": "Digital TV Europe",
  "streamingmedia.com": "Streaming Media",
  "broadcastingcable.com": "Broadcasting+Cable",
  "nexttv.com": "NextTV",
  "protocol.com": "Protocol",
  "axios.com": "Axios",
  "cnbc.com": "CNBC",
  "theinformation.com": "The Information",
  "engadget.com": "Engadget",
  "arstechnica.com": "Ars Technica",
};

function titleCaseLabel(label: string): string {
  if (!label) return label;
  return label.charAt(0).toUpperCase() + label.slice(1);
}

// "press.adobe.com" -> "adobe.com" (drop a subdomain, keep the registrable
// domain) before falling back to a title-cased guess. Not a full public-
// suffix-list implementation (e.g. "bbc.co.uk" would over-strip to "co.uk")
// — known two-part domains like that are already covered by the lookup
// table above, so this fallback only runs for domains not already handled.
function registrableDomain(hostname: string): string {
  const parts = hostname.split(".");
  return parts.length > 2 ? parts.slice(-2).join(".") : hostname;
}

export function publisherLabel(sourceUrl: string | null, fallbackTitle: string | null): string | null {
  if (sourceUrl) {
    try {
      const hostname = new URL(sourceUrl).hostname.replace(/^www\./, "").toLowerCase();
      if (KNOWN_PUBLISHERS[hostname]) return KNOWN_PUBLISHERS[hostname];

      const domain = registrableDomain(hostname);
      const dotIndex = domain.indexOf(".");
      const label = dotIndex === -1 ? domain : domain.slice(0, dotIndex);
      const suffix = dotIndex === -1 ? "" : domain.slice(dotIndex);
      return `${titleCaseLabel(label)}${suffix}`;
    } catch {
      // Malformed source_url — fall through to the title-based fallback.
    }
  }
  return fallbackTitle;
}
